#!/usr/bin/env python3
"""
Harvey AI - Data Scientist Agent CLI
Analyzes Azure SQL database and recommends ML improvements.

Usage:
    # Run full analysis
    python scripts/data_scientist_agent.py --analyze

    # Quick schema analysis only
    python scripts/data_scientist_agent.py --schema-only
    
    # Generate recommendations only
    python scripts/data_scientist_agent.py --recommendations-only
    
    # Save report to file
    python scripts/data_scientist_agent.py --analyze --output report.json
"""

import sys
import os
import json
import argparse
from pathlib import Path
from datetime import datetime
from typing import Dict, Any

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from dotenv import load_dotenv
load_dotenv(override=True)

from app.services.data_scientist_agent import data_scientist_agent


def print_banner():
    """Print CLI banner."""
    print("=" * 80)
    print("🔬 Harvey AI - Data Scientist Agent")
    print("=" * 80)
    print()


def print_section(title: str):
    """Print section header."""
    print()
    print("─" * 80)
    print(f"📊 {title}")
    print("─" * 80)


def format_number(num: float) -> str:
    """Format number with commas."""
    if isinstance(num, float):
        return f"{num:,.2f}"
    return f"{num:,}"


def print_schema_summary(schema: Dict[str, Any]):
    """Print schema analysis summary."""
    print_section("Database Schema Analysis")
    
    print(f"Total Tables: {schema.get('total_tables', 0)}")
    print()
    
    tables = schema.get("tables", {})
    for table_name, table_info in sorted(tables.items()):
        print(f"  📁 {table_name}")
        print(f"     Columns: {table_info.get('columns', 0)}")
        print(f"     Indexes: {table_info.get('indexes', 0)}")
        print(f"     Foreign Keys: {table_info.get('foreign_keys', 0)}")


def print_distribution_summary(distribution: Dict[str, Any]):
    """Print data distribution summary."""
    print_section("Data Distribution Analysis")
    
    print(f"Total Rows Across All Tables: {format_number(distribution.get('total_rows', 0))}")
    print()
    
    for table_name, info in sorted(distribution.items()):
        if isinstance(info, dict) and "row_count" in info:
            status = "✓" if info.get("exists") else "✗"
            count = format_number(info["row_count"])
            print(f"  {status} {table_name:.<40} {count:>15} rows")


def print_coverage_summary(coverage: Dict[str, Any]):
    """Print training coverage summary."""
    print_section("Training Data Coverage")
    
    print(f"Total Categories: {coverage.get('total_categories', 0)}")
    print(f"Total Questions: {format_number(coverage.get('total_questions', 0))}")
    print(f"Avg Questions/Category: {format_number(coverage.get('average_questions_per_category', 0))}")
    print()
    
    categories = coverage.get("categories", [])
    if categories:
        print("Category Breakdown:")
        for cat in categories:
            processed_pct = cat.get('processed_rate', 0) * 100
            bar_length = int(cat.get('question_count', 0) / 10)
            bar = "█" * min(bar_length, 50)
            print(f"  {cat['category']:.<35} {cat['question_count']:>6} ({processed_pct:>5.1f}% processed)")


def print_performance_summary(performance: Dict[str, Any]):
    """Print model performance summary."""
    print_section("Model Performance Analysis")
    
    print(f"Total Models: {performance.get('total_models', 0)}")
    print(f"Total Responses: {format_number(performance.get('total_responses', 0))}")
    print(f"Best Quality Model: {performance.get('best_quality_model', 'N/A')}")
    print()
    
    models = performance.get("models", [])
    if models:
        print(f"{'Model':<20} {'Responses':<12} {'Avg Time (ms)':<15} {'Quality':<10} {'Confidence':<10}")
        print("─" * 80)
        for model in models:
            print(f"{model['model']:<20} "
                  f"{format_number(model['response_count']):<12} "
                  f"{format_number(model['avg_response_time_ms']):<15} "
                  f"{format_number(model['avg_quality_score']):<10} "
                  f"{format_number(model['avg_confidence']):<10}")


def print_recommendations(recommendations: Dict[str, Any]):
    """Print ML recommendations."""
    print_section("AI-Powered ML Recommendations")
    
    if "error" in recommendations:
        print(f"❌ Error generating recommendations: {recommendations['error']}")
        return
    
    print(f"Generated by: {recommendations.get('model_used', 'Unknown')}")
    print(f"Timestamp: {recommendations.get('timestamp', 'Unknown')}")
    print()
    
    sections = [
        ("new_ml_models", "🤖 New ML Models to Implement"),
        ("training_improvements", "📚 Training Data Improvements"),
        ("feature_engineering", "🔧 Feature Engineering Ideas"),
        ("model_optimization", "⚡ Model Optimization"),
        ("data_quality", "✅ Data Quality Improvements"),
        ("performance", "🚀 Performance Enhancements")
    ]
    
    for key, title in sections:
        items = recommendations.get(key, [])
        if items:
            print(f"\n{title}:")
            for i, item in enumerate(items, 1):
                if isinstance(item, dict):
                    print(f"  {i}. {item.get('title', item.get('name', 'Unnamed'))}")
                    if 'description' in item:
                        print(f"     → {item['description']}")
                    if 'priority' in item:
                        print(f"     Priority: {item['priority']}")
                else:
                    print(f"  {i}. {item}")
    
    if "raw_text" in recommendations:
        print("\nFull Recommendations:")
        print(recommendations["raw_text"])


def save_report(report: Dict[str, Any], output_path: str):
    """Save analysis report to file."""
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    
    print()
    print(f"✓ Report saved to: {output_file}")
    print(f"  File size: {output_file.stat().st_size:,} bytes")


def main():
    parser = argparse.ArgumentParser(
        description="Harvey AI Data Scientist Agent - Analyze database and recommend ML improvements",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        '--analyze',
        action='store_true',
        help='Run full database analysis and generate recommendations'
    )
    
    parser.add_argument(
        '--schema-only',
        action='store_true',
        help='Analyze database schema only'
    )
    
    parser.add_argument(
        '--distribution-only',
        action='store_true',
        help='Analyze data distribution only'
    )
    
    parser.add_argument(
        '--coverage-only',
        action='store_true',
        help='Analyze training coverage only'
    )
    
    parser.add_argument(
        '--performance-only',
        action='store_true',
        help='Analyze model performance only'
    )
    
    parser.add_argument(
        '--recommendations-only',
        action='store_true',
        help='Generate ML recommendations only (requires prior analysis)'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        help='Output file path for JSON report (default: auto-generated in attached_assets/)'
    )
    
    parser.add_argument(
        '--quiet',
        action='store_true',
        help='Suppress console output, only save to file'
    )
    
    args = parser.parse_args()
    
    if not args.quiet:
        print_banner()
    
    report = {}
    
    try:
        if args.analyze:
            if not args.quiet:
                print("🔬 Running full database analysis...")
                print("   This may take 30-60 seconds...")
                print()
            
            report = data_scientist_agent.run_full_analysis()
            
            if not args.quiet:
                print_schema_summary(report.get("schema_analysis", {}))
                print_distribution_summary(report.get("data_distribution", {}))
                print_coverage_summary(report.get("training_coverage", {}))
                print_performance_summary(report.get("model_performance", {}))
                print_recommendations(report.get("ml_recommendations", {}))
        
        elif args.schema_only:
            report["schema_analysis"] = data_scientist_agent.analyze_database_schema()
            if not args.quiet:
                print_schema_summary(report["schema_analysis"])
        
        elif args.distribution_only:
            report["data_distribution"] = data_scientist_agent.analyze_data_distribution()
            if not args.quiet:
                print_distribution_summary(report["data_distribution"])
        
        elif args.coverage_only:
            report["training_coverage"] = data_scientist_agent.analyze_training_coverage()
            if not args.quiet:
                print_coverage_summary(report["training_coverage"])
        
        elif args.performance_only:
            report["model_performance"] = data_scientist_agent.analyze_model_performance()
            if not args.quiet:
                print_performance_summary(report["model_performance"])
        
        elif args.recommendations_only:
            if not args.quiet:
                print("🤖 Generating ML recommendations using Gemini 2.0...")
                print("   This may take 10-20 seconds...")
                print()
            
            data_scientist_agent.analyze_database_schema()
            data_scientist_agent.analyze_data_distribution()
            data_scientist_agent.analyze_training_coverage()
            data_scientist_agent.analyze_model_performance()
            
            report["ml_recommendations"] = data_scientist_agent.generate_ml_recommendations()
            if not args.quiet:
                print_recommendations(report["ml_recommendations"])
        
        else:
            parser.print_help()
            return
        
        if args.output:
            save_report(report, args.output)
        elif report and not args.quiet:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            default_output = f"attached_assets/data_scientist_report_{timestamp}.json"
            save_report(report, default_output)
        
        if not args.quiet:
            print()
            print("=" * 80)
            print("✅ Analysis Complete!")
            print("=" * 80)
    
    except Exception as e:
        print(f"\n❌ Error during analysis: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
